on:
  schedule:
    - cron: '* * * * *'   # run every minute for testing
  workflow_dispatch: {}
jobs:
  say-time:
    runs-on: ubuntu-latest
    steps:
      - run: date && echo "SCHEDULED RUN: $(date)"